[project]
type = "contract"
name = "algoflow"

[project.deploy]
command = "poetry run python -m smart_contracts.payroll_stream.deploy_config"
environment_secrets = ["DEPLOYER_MNEMONIC"]

[project.run.build]
command = "algokit compile python smart_contracts/payroll_stream/contract.py"
description = "Compile the PayrollStream contract"

[project.run.test]
command = "pytest"
description = "Run smart contract tests"

[generate.smart_contract]
description = "Algorand Python smart contract"
path = "smart_contracts"
